namespace BreweryMaster.Tests.Models
{
    public static class TestConst
    {
        public const string String = "TestString";
        public const string String256Characters = "qolnktggqdrisbyatesphjrrevbmoownetttbagvvdlyaheyuncqtexubvhnszszabcbonfzdzowzqlyjflwwgvbnpgbljfqkuumybhvodudydhzqccxdwlczierzxbioequuenipgakyktgsdpecmswowvakgswjdqlkpfojgtedcthkgptsbmjmpiqarxhfxxbhgxczyyphacnayxguqfwvwqzjpyqhotijdzfedmftccptmgorvnkqpmljtbh";
        public const string String257Characters = "aqolnktggqdrisbyatesphjrrevbmoownetttbagvvdlyaheyuncqtexubvhnszszabcbonfzdzowzqlyjflwwgvbnpgbljfqkuumybhvodudydhzqccxdwlczierzxbioequuenipgakyktgsdpecmswowvakgswjdqlkpfojgtedcthkgptsbmjmpiqarxhfxxbhgxczyyphacnayxguqfwvwqzjpyqhotijdzfedmftccptmgorvnkqpmljtbh";
        public const string String450Characters = "ipchbalugywjzfdcqkexabdpvcmslokommfbxwxvzcbrursjhrerbykrgvrznpniwtucqrgldyoogqigzjuoahrjbvtilmqpluemdjkavkkwtqodiqnnbmebydaaednvzstderipagzyxtjxvteywyuoyfsabdhcqugpjkpiksfbjxbolereumjfwsdtwdjbelgowsqshadmdzyqdjhawhlraydjeuqcnswvlhyvhpijbbdpisnxmyhzauxcnrmpzstpnqjlqcfmqodddavqlgexmarpdpphcfrvlettrarazwnwqmzqdzcwtvcssdewjzftwdtdfstugjgsnmmrjafvphqnjcerhjeewcmxhlgqpzmvhjltwbxahcyudjbmroajslvyesmyoxxzzmzykocumlttgtnzsejnlgrmoflfriizgshezuagwvpbxjagkb";
        public const string String451Characters = "aipchbalugywjzfdcqkexabdpvcmslokommfbxwxvzcbrursjhrerbykrgvrznpniwtucqrgldyoogqigzjuoahrjbvtilmqpluemdjkavkkwtqodiqnnbmebydaaednvzstderipagzyxtjxvteywyuoyfsabdhcqugpjkpiksfbjxbolereumjfwsdtwdjbelgowsqshadmdzyqdjhawhlraydjeuqcnswvlhyvhpijbbdpisnxmyhzauxcnrmpzstpnqjlqcfmqodddavqlgexmarpdpphcfrvlettrarazwnwqmzqdzcwtvcssdewjzftwdtdfstugjgsnmmrjafvphqnjcerhjeewcmxhlgqpzmvhjltwbxahcyudjbmroajslvyesmyoxxzzmzykocumlttgtnzsejnlgrmoflfriizgshezuagwvpbxjagkb";
    }
}
